baseurl: /

theme: jekyll-theme-hacker

title: Luo Xiaolei's blog
email: coderluoxiaolei@gmail.com
description: Share my bugs I met.

twitter_username: xiaoleiluo
github_username:  luoxiaolei

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed